routes/web.php
    Route::delete('category/{id}', 'CategoryController@destroy')->name('category.destroy');

    //create index
    Route::get('comment', 'CommentController@index')->name('comment.index');
//create form
    Route::get('comment/create', 'CommentController@create')->name('comment.create');
//store into database
    Route::post('comment', 'CommentController@store')->name('comment.store');
//view details
    Route::get('comment/{id}', 'CommentController@show')->name('comment.show');
//edit form
    Route::get('comment/{id}/edit', 'CommentController@edit')->name('comment.edit');
//update into database
    Route::put('comment/{id}', 'CommentController@update')->name('comment.update');
//delete form database
    Route::delete('comment/{id}', 'CommentController@destroy')->name('comment.destroy');

    Route::get('configuration', 'ConfigurationController@index')->name('configuration.index');
//create form
    Route::get('configuration/create', 'ConfigurationController@create')->name('configuration.create');
//store into database
    Route::post('configuration', 'ConfigurationController@store')->name('configuration.store');
//view details
    Route::get('configuration/{id}', 'ConfigurationController@show')->name('configuration.show');
//edit form
    Route::get('configuration/{id}/edit', 'ConfigurationController@edit')->name('configuration.edit');
//update into database
    Route::put('configuration/{id}', 'ConfigurationController@update')->name('configuration.update');
//delete form database
    Route::delete('configuration/{id}', 'ConfigurationController@destroy')->name('configuration.destroy');

    //module
    Route::get('video', 'VideoController@index')->name('video.index');
//create form
    Route::get('video/create', 'VideoController@create')->name('video.create');
//store into database
    Route::post('video', 'VideoController@store')->name('video.store');
//view details
    Route::get('video/{id}', 'VideoController@show')->name('video.show');
//edit form
    Route::get('video/{id}/edit', 'VideoController@edit')->name('video.edit');
//update into database
    Route::put('video/{id}', 'VideoController@update')->name('video.update');
//delete form database
    Route::delete('video/{id}', 'VideoController@destroy')->name('video.destroy');
    //index
    Route::get('configuration', 'ConfigurationController@index')->name('configuration.index');
//create form
    Route::get('configuration/create', 'ConfigurationController@create')->name('configuration.create');
//store into database
    Route::post('configuration', 'ConfigurationController@store')->name('configuration.store');
//view details
    Route::get('configuration/{id}', 'ConfigurationController@show')->name('configuration.show');
//edit form
    Route::get('configuration/{id}/edit', 'ConfigurationController@edit')->name('configuration.edit');
//update into database
    Route::put('configuration/{id}', 'ConfigurationController@update')->name('configuration.update');
//delete form database
    Route::delete('configuration/{id}', 'ConfigurationController@destroy')->name('configuration.destroy');

    //module
    Route::get('module', 'ModuleController@index')->name('module.index');
//create form
    Route::get('module/create', 'ModuleController@create')->name('module.create');
//store into database
    Route::post('module', 'ModuleController@store')->name('module.store');
//view details
    Route::get('module/{id}', 'ModuleController@show')->name('module.show');
//edit form
    Route::get('module/{id}/edit', 'ModuleController@edit')->name('module.edit');
//update into database
    Route::put('module/{id}', 'ModuleController@update')->name('module.update');
//delete form database
    Route::delete('module/{id}', 'ModuleController@destroy')->name('module.destroy');


    //create index
    Route::get('news', 'NewsController@index')->name('news.index');
//create form
    Route::get('news/create', 'NewsController@create')->name('news.create');
//store into database
    Route::post('news', 'NewsController@store')->name('news.store');
//view details
    Route::get('news/{id}', 'NewsController@show')->name('news.show');
//edit form
    Route::get('news/{id}/edit', 'NewsController@edit')->name('news.edit');
//update into database
    Route::put('news/{id}', 'NewsController@update')->name('news.update');
//delete form database
    Route::delete('news/{id}', 'NewsController@destroy')->name('news.destroy');

    Route::get('/search', 'NewsController@search')->name('news.search');


    //create index
    Route::get('newstype', 'NewsTypeController@index')->name('newstype.index');
//create form
    Route::get('newstype/create', 'NewsTypeController@create')->name('newstype.create');
//store into database
    Route::post('newstype', 'NewsTypeController@store')->name('newstype.store');
//view details
    Route::get('newstype/{id}', 'NewsTypeController@show')->name('newstype.show');
//edit form
    Route::get('newstype/{id}/edit', 'NewsTypeController@edit')->name('newstype.edit');
//update into database
    Route::put('newstype/{id}', 'NewsTypeController@update')->name('newstype.update');
//delete form database
    Route::delete('newstype/{id}', 'NewsTypeController@destroy')->name('newstype.destroy');


    //create index
    Route::get('news_slider', 'NewsSliderController@index')->name('news_slider.index');
//create form
    Route::get('news_slider/create', 'NewsSliderController@create')->name('news_slider.create');
//store into database
    Route::post('news_slider', 'NewsSliderController@store')->name('news_slider.store');
//view details
    Route::get('news_slider/{id}', 'NewsSliderController@show')->name('news_slider.show');
//edit form
    Route::get('news_slider/{id}/edit', 'NewsSliderController@edit')->name('news_slider.edit');
//update into database
    Route::put('news_slider/{id}', 'NewsSliderController@update')->name('news_slider.update');
//delete form database
    Route::delete('news_slider/{id}', 'NewsSliderController@destroy')->name('news_slider.destroy');

    //create index
    Route::get('page', 'PageController@index')->name('page.index');
//create form
    Route::get('page/create', 'PageController@create')->name('page.create');
//store into database
    Route::post('page', 'PageController@store')->name('page.store');
//view details
    Route::get('page/{id}', 'PageController@show')->name('page.show');
//edit form
    Route::get('page/{id}/edit', 'PageController@edit')->name('page.edit');
//update into database
    Route::put('page/{id}', 'PageController@update')->name('page.update');
//delete form database
    Route::delete('page/{id}', 'PageController@destroy')->name('page.destroy');

    //permissions
    Route::get('permission', 'PermissionController@index')->name('permission.index');
//create form
    Route::get('permission/create', 'PermissionController@create')->name('permission.create');
//store into database
    Route::post('permission', 'PermissionController@store')->name('permission.store');
//view details
    Route::get('permission/{id}', 'PermissionController@show')->name('permission.show');
//edit form
    Route::get('permission/{id}/edit', 'PermissionController@edit')->name('permission.edit');
//update into database
    Route::put('permission/{id}', 'PermissionController@update')->name('permission.update');
//delete form database
    Route::delete('permission/{id}', 'PermissionController@destroy')->name('permission.destroy');


    //role
    Route::get('role', 'RoleController@index')->name('role.index');
//create form
    Route::get('role/create', 'RoleController@create')->name('role.create');
//store into database
    Route::post('role', 'RoleController@store')->name('role.store');
//view details
    Route::get('role/{id}', 'RoleController@show')->name('role.show');
//edit form
    Route::get('role/{id}/edit', 'RoleController@edit')->name('role.edit');
//update into database
    Route::put('role/{id}', 'RoleController@update')->name('role.update');
//delete form database
    Route::delete('role/{id}', 'RoleController@destroy')->name('role.destroy');

    Route::get('role/assignpermission/{id}', 'RoleController@assignPermission')->name('role.assignpermission');

    Route::post('role/savepermission/{id}', 'RoleController@savePermission')->name('role.savepermission');


    //index
    Route::get('tag', 'TagController@index')->name('tag.index');
//create form
    Route::get('tag/create', 'TagController@create')->name('tag.create');
//store into database
    Route::post('tag', 'TagController@store')->name('tag.store');
//view details
    Route::get('tag/{id}', 'TagController@show')->name('tag.show');
//edit form
    Route::get('tag/{id}/edit', 'TagController@edit')->name('tag.edit');
//update into database
    Route::put('tag/{id}', 'TagController@update')->name('tag.update');
//delete form database
    Route::delete('tag/{id}', 'TagController@destroy')->name('tag.destroy');

    //create index
    Route::get('user', 'UserController@index')->name('user.index');
//create form
    Route::get('user/create', 'UserController@create')->name('user.create');
//store into database
    Route::post('user', 'UserController@store')->name('user.store');
//view details
    Route::get('user/{id}', 'UserController@show')->name('user.show');
//edit form
    Route::get('user/{id}/edit', 'UserController@edit')->name('user.edit');
//update into database
    Route::put('user/{id}', 'UserController@update')->name('user.update');
//delete form database
    Route::delete('user/{id}', 'UserController@destroy')->name('user.destroy');


});
Route::get('/profile', 'HomeController@profile')->name('backend.profile');




Auth::routes();

Route::post('/profile', 'ProfileController@profile')->name('home.profile');
//Route::post('profile/change-password', 'ProfileController@password')->name('profile.change_password');
Route::resource('/tasks','TaskController');
Route::get('/home', 'HomeController@index')->name('home');

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{

}

app/Http/Controllers/TaskController.php
<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Task;
use Session;
class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//        $tasks = Task::orderBy('id','desc')->paginate(5);
//        return view('tasks.index')->with('storedTasks', $tasks);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
//    public function store(Request $request)
//    {
//        $this->validate($request, [
//            'newTaskName' => 'required|min:5|max:255',
//        ]);
//        $task = new Task;
//        $task->name = $request->newTaskName;
//        $task->save();
//        Session::flash('success', 'New task has been succesfully added!');
//        return redirect()->route('home');
//    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $task = Task::find($id);
        return view('tasks.edit')->with('taskUnderEdit', $task);
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'updatedTaskName' => 'required|min:5|max:255',
        ]);
        $task = Task::find($id);
        $task->name = $request->updatedTaskName;
        $task->save();
        Session::flash('success', 'Task #' . $id . ' has been successfully updated.');
        return redirect()->route('tasks.index');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
//    public function destroy($id)
//    {
//        $task = Task::find($id);
//        $task->delete();
//        Session::flash('success', 'Task #' . $id . ' has been successfully deleted.');
//        return redirect()->route('tasks.index');
//    }
}

resources/views/tasks/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    {{-- bootstrap css CDN --}}
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    {{-- bootstrap js CDN --}}
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <title>Todo List App</title>
</head>
<body>
<div class="container">
    <div class="col-md-offset-2 col-md-8">
        <div class="row">
            <h1>Todo List</h1>
        </div>

        {{-- display success message --}}
        @if (Session::has('success'))
            <div class="alert alert-success">
                <strong>Success:</strong> {{ Session::get('success') }}
            </div>
        @endif

        {{-- display error message --}}
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Error:</strong>
                <ul>
                    @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <div class="row">
            <form action="{{ route('tasks.update', [$taskUnderEdit->id]) }}" method='POST'>
                {{ csrf_field() }}
                <input type="hidden" name='_method' value='PUT'>

                <div class="form-group">
                    <input type="text" name='updatedTaskName' class='form-control input-lg' value='{{ $taskUnderEdit->name }}'>
                </div>

                <div class="form-group">
                    <input type="submit" value='Save Changes' class='btn btn-success btn-lg'>
                    <a href="" class='btn btn-danger btn-lg pull-right'>Go Back</a>
                </div>
            </form>
        </div>


    </div>
</div>
</body>
</html>

resources/views/tasks/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    {{-- bootstrap css CDN --}}
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    {{-- bootstrap js CDN --}}
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <title>Todo List App</title>
</head>
<body>
<div class="container">
    <div class="col-md-offset-2 col-md-8">
        <div class="row">
            <h1>Todo List</h1>
        </div>

        {{-- display success message --}}
        @if (Session::has('success'))
            <div class="alert alert-success">
                <strong>Success:</strong> {{ Session::get('success') }}
            </div>
        @endif

        {{-- display error message --}}
        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Error:</strong>
                <ul>
                    @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        {{--<div class="row" style='margin-top: 10px; margin-bottom: 10px;'>--}}
            {{--<form action="{{ route('tasks.store') }}" method='POST'>--}}
                {{--{{ csrf_field() }}--}}

                {{--<div class="col-md-9">--}}
                    {{--<input type="text" name='newTaskName' class='form-control'>--}}
                {{--</div>--}}

                {{--<div class="col-md-3">--}}
                    {{--<input type="submit" class='btn btn-primary btn-block' value='Add Task'>--}}
                {{--</div>--}}
            {{--</form>--}}
        {{--</div>--}}

        {{-- display stored tasks --}}
        @if (count($storedTasks) > 0)
            <table class="table">
                <thead>
                <th>Task #</th>
                <th>Name</th>
                <th>Edit</th>
                <th>Delete</th>
                </thead>

                <tbody>
                @foreach ($storedTasks as $storedTask)
                    <tr>
                        <th>{{ $storedTask->id }}</th>
                        <td>{{ $storedTask->name }}</td>
                        <td><a href="{{ route('tasks.edit', ['tasks'=>$storedTask->id]) }}" class='btn btn-default'>Edit</a></td>
                        <td>
                            <form action="{{ route('tasks.destroy', ['tasks'=>$storedTask->id]) }}" method='POST'>
                                {{ csrf_field() }}
                                <input type="hidden" name='_method' value='DELETE'>

                                <input type="submit" class='btn btn-danger' value='Delete'>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        @endif

        <div class="row text-center">
            {{ $storedTasks->links() }}
        </div>

    </div>
</div>
</body>
</html>